// Generated by Makefile. Do not edit.
enum BuildInfo {
    static let version = "1.0.0"
    static let buildDate = "2026-08-25T16:53:05Z"
    static let buildSeq = 4
    static let commit = "f2c9ffd"
}
