// Generated by Makefile. Do not edit.
enum BuildInfo {
    static let version = "1.1.3"
    static let buildDate = "2026-09-11T17:45:31Z"
    static let buildSeq = 5
    static let commit = "873e1fd"
}
